### ISSUE TITLE
Adding Widget for inline errors

### ISSUE THREAD

**Issue by puzzledShark** [cdot-brackets-extensions/nimble-htmlLint#10]
Ideally we would like the inline warning to be a clickable button for the user to interact with and receive an error upon clicking. For feature #9 we need to also include a widget to display the error for the user to read.
An example of such is below:
https://camo.githubusercontent.com/e6bf3f2527f3171ab3e32fd11a19b83056719009/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f313036303131392f3133373736342f34393532626637302d373137612d313165322d383738342d3738656537633632363662612e706e67

**Comment by sedge** [comment]
Ditto here.
