### ISSUE TITLE
Making error message more helpful

### ISSUE THREAD

**Issue by AJDBenner** [cdot-brackets-extensions/nimble-htmlLint#8]
In the parser.js file, within the errorJSON object, error messages from INVALID_CSS_DECLARATION to error message UNTERMINATED_OPEN_TAG are incomplete and contain snippets of code that doesn't execute. The messages need to be completed and the code within the messages needs to execute.

**Comment by humphd** [comment]
Speaking of "making things more helpful" this bug needs a full description.  When you file bugs, make sure that someone random from the web could come along, read what you've written, and help work on it.  If they need to talk to you to get more details, we've failed.
