### ISSUE TITLE
Add inline warnings for parse errors

### ISSUE THREAD

**Issue by puzzledShark** [cdot-brackets-extensions/nimble-htmlLint#9]
Currently the errors displayed to the user are not user friendly/efficient enough. To aliviate this research and implementation of a inline warning similar to thimble or the code mirror example linked below.

Refer to http://codemirror.net/demo/lint.html for an example of inline warnings for parse errors.

**Comment by sedge** [comment]
Get in the habit of detailing your issues. Don't leave them blank!

**Comment by sedge** [comment]
See: https://github.com/cdot-brackets-extensions/nimble-htmlLint/issues/8#issuecomment-69933357
